---
- name: Setup WordPress server
  hosts: all
  gather_facts: no

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  pre_tasks:
    - name: "Check custom SSH port availability"
      tags:
        - always
        - ssh_port
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        state: "started"
        timeout: 1
      delegate_to: "localhost"
      become: false
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: ssh_port_custom

    - name: "Check default SSH port availability"
      tags:
        - always
        - ssh_port
      wait_for:
        host: "{{ ansible_host }}"
        port: "22"
        state: "started"
        timeout: 1
      delegate_to: "localhost"
      become: false
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: ssh_port_default
      when:
        - ssh_port_custom.state is not defined

    - name: "Fail if host not available"
      tags:
        - always
        - ssh_port
      fail:
        msg: |
          Can't connect with neither custom nor default SSH ports to {{ inventory_hostname }} ({{ ansible_host }}).
          Is the host up?
      when:
        - ssh_port_custom.state is not defined
        - ssh_port_default.state is not defined

    - name: "Set SSH port to default if needed"
      tags:
        - always
        - ssh_port
      set_fact:
        ansible_user: "root"
        ansible_port: "22"
      changed_when: false
      when:
        - ssh_port_custom.state is not defined

    - name: "Debug SSH port (ansible_port)"
      tags:
        - debug
        - ssh_port
      debug:
        var: ansible_port

    - name: "Gather facts after setting SSH port"
      tags:
        - always
      setup:

    - name: "Fail if host distro is not supported"
      tags:
        - always
      fail:
        msg: |
          Unsupported host system: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }} ({{ ansible_facts['os_family'] }}).
          Check documentation for more info about supported systems.
      when: >
        ansible_facts['distribution'] not in [
          'Ubuntu',
        ]

    - name: "Include task to set distro specific variables"
      tags:
        - always
      include_tasks: tasks/set_vars.yml

  tasks:
    - name: "Common configuration"
      tags:
        - always
        - setup
        - common
      import_role:
        name: common
      become: true

    - name: "SSH configuration"
      tags:
        - setup
        - ssh
      import_role:
        name: ssh_config
      become: true

    - name: "UFW installation and configuration"
      tags:
        - setup
        - ufw
      import_role:
        name: ufw_config
      become: true

    - name: "Docker installation and configuration"
      tags:
        - setup
        - docker
      import_role:
        name: docker_setup
      become: true
