---
- name: Setup WordPress server
  hosts: all
  gather_facts: no

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  pre_tasks:
    - name: "Check custom SSH port availability"
      tags:
        - always
        - ssh_port
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        state: "started"
        timeout: 1
      delegate_to: "localhost"
      become: false
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: ssh_port_custom

    - name: "Check default SSH port availability"
      tags:
        - always
        - ssh_port
      wait_for:
        host: "{{ ansible_host }}"
        port: "22"
        state: "started"
        timeout: 1
      delegate_to: "localhost"
      become: false
      ignore_errors: true
      changed_when: false
      failed_when: false
      register: ssh_port_default
      when:
        - ssh_port_custom.state is not defined

    - name: "Fail if host not available"
      tags:
        - always
        - ssh_port
      fail:
        msg: |
          Can't connect with neither custom nor default SSH ports to {{ inventory_hostname }} ({{ ansible_host }}).
          Is the host up?
      when:
        - ssh_port_custom.state is not defined
        - ssh_port_default.state is not defined

    - name: "Set SSH port to default if needed"
      tags:
        - always
        - ssh_port
      set_fact:
        ansible_user: "root"
        ansible_port: "22"
      changed_when: false
      when:
        - ssh_port_custom.state is not defined

    - name: "Debug ansible_port"
      tags:
        - debug
        - ssh_port
      debug:
        var: ansible_port
