default_users:
  - username: ansible
    # password not defined, locked user (only for ssh via auth-key)
    authorized_key: "{{ vault_ansible_user_authorized_key }}" # in `vault.yml`
    is_sudo: true
    is_sudo_nopasswd: true
  - username: admin
    password: "{{ vault_admin_user_password }}"  # in `vault.yml`
    authorized_key: "{{ vault_admin_user_authorized_key }}" # in `vault.yml`
    shell: "/bin/bash"
    create_home: true
    is_sudo: true
    is_sudo_nopasswd: false

default_user_shell: "/bin/bash"
