- name: "Include Ubuntu 20 specific variables"
  include_vars:
    file: distro/ubuntu-20.yml
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
    - ansible_facts['distribution_major_version'] == '20'
