FROM alpine:{{ alpine_version }}

ENV DB_HOST="127.0.0.1"

RUN apk update && apk upgrade && apk add --no-cache \
		wget				\
		tar					\
		mariadb-client		\
		redis				\
		# WORDPRESS
		php7				\
		php7-fpm			\
		php7-bcmath			\
		php7-bz2 			\
		php7-calendar		\
		php7-ctype			\
		php7-curl			\
		php7-dom			\
		php7-exif			\
		php7-fileinfo		\
		php7-gd				\
		php7-gmagick		\
		php7-gmp			\
		php7-iconv			\
		php7-imap			\
		php7-intl			\
		php7-json			\
		php7-mbstring		\
		php7-mcrypt			\
		php7-memcache		\
		php7-mysqli			\
		php7-mysqlnd		\
		php7-openssl		\
		php7-pcntl			\
		php7-pdo			\
		php7-pdo_mysql		\
		php7-pdo_pgsql		\
		php7-pdo_sqlite 	\
		php7-pgsql			\
		php7-phar			\
		php7-posix			\
		php7-session		\
		php7-shmop			\
		php7-simplexml		\
		php7-soap			\
		php7-sockets		\
		php7-sodium			\
		php7-sqlite3		\
		php7-sysvsem		\
		php7-sysvshm		\
		php7-tokenizer		\
		php7-xml			\
		php7-xmlreader		\
		php7-xmlwriter		\
		php7-xsl			\
		php7-zip			\
		php7-zlib	

#	bash less vim nano git mariadb-client ca-certificates \
#	php7 php7-fpm php7-json php7-zlib php7-xml php7-pdo php7-phar php7-openssl \
#	php7-pdo_mysql php7-mysqli php7-mysqlnd \
#	php7-gd php7-mcrypt \
#	php7-curl php7-opcache php7-ctype  \
#	php7-intl php7-bcmath php7-dom php7-xmlreader

# php fpm
RUN adduser -S nginx && addgroup -S nginx
COPY php-fpm.conf /etc/php7/php-fpm.conf
COPY www.conf /etc/php7/php-fpm.d/www.conf

# wordpress
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
	&& chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && chmod +x /usr/local/bin/wp

WORKDIR /var/www/html/wordpress

EXPOSE {{ wordpress_phpfpm_port }}

COPY run.sh /tmp/run.sh
CMD ["sh", "/tmp/run.sh"]
