---
- name: "Update package cache (Family: Debian)"
  tags:
    - packages
  apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == 'Debian'

- name: "Install common packages (Family: Debian)"
  tags:
    - packages
  apt:
    name: "{{ common_packages }}"
    state: present
  when: ansible_facts['os_family'] == 'Debian'
