---
- name: "Create users"
  tags:
    - users
  user:
    name: "{{ item.username }}"
    state: present
    groups: "{{ 'sudo' if item.is_sudo else omit }}"
    append: true
    password: "{{ (item.password | default('') | password_hash('sha512')) if item.password is defined else omit }}"
    update_password: on_create
    create_home: true
  no_log: "{{ ansible_verbosity < 1 }}"
  with_items: "{{ users }}"

- name: "Set or update user passwords"
  tags:
    - users
  user:
    name: "{{ item.username }}"
    password: "{{ (item.password | default('') | password_hash('sha512')) if item.password is defined else omit }}"
    update_password: always
  no_log: "{{ ansible_verbosity < 1 }}"
  when: item.password is defined and (update_passwords | default(false))
  with_items: "{{ users }}"
