---
- name: "Build Docker Images"
  docker_image:
    name: "cloud1_{{ item.name }}"
    tag: latest
    state: present
    source: build
    build:
      path: "{{ deploy_path }}/{{ item.name }}"
      nocache: false
      rm: true
  loop: "{{ containers }}"
